/*
 * Jaqpot API
 * Jaqpot v4 (Quattro) is the 4th version of a YAQP, a RESTful web service which can be used to train machine learning models and use them to obtain toxicological predictions for given chemical compounds or engineered nano materials. The project is written in Java8 and JEE7.
 *
 * OpenAPI spec version: 4.0.3
 * Contact: hampos@me.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package jaqpot.client.model;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModelProperty;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * ArrayCalculation
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2017-02-09T12:17:06.729Z")
public class ArrayCalculation {
  @SerializedName("colNames")
  private List<String> colNames = new ArrayList<String>();

  @SerializedName("values")
  private Map<String, List<Object>> values = new HashMap<String, List<Object>>();

  public ArrayCalculation colNames(List<String> colNames) {
    this.colNames = colNames;
    return this;
  }

  public ArrayCalculation addColNamesItem(String colNamesItem) {
    this.colNames.add(colNamesItem);
    return this;
  }

   /**
   * Get colNames
   * @return colNames
  **/
  @ApiModelProperty(example = "null", value = "")
  public List<String> getColNames() {
    return colNames;
  }

  public void setColNames(List<String> colNames) {
    this.colNames = colNames;
  }

  public ArrayCalculation values(Map<String, List<Object>> values) {
    this.values = values;
    return this;
  }

  public ArrayCalculation putValuesItem(String key, List<Object> valuesItem) {
    this.values.put(key, valuesItem);
    return this;
  }

   /**
   * Get values
   * @return values
  **/
  @ApiModelProperty(example = "null", value = "")
  public Map<String, List<Object>> getValues() {
    return values;
  }

  public void setValues(Map<String, List<Object>> values) {
    this.values = values;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ArrayCalculation arrayCalculation = (ArrayCalculation) o;
    return Objects.equals(this.colNames, arrayCalculation.colNames) &&
        Objects.equals(this.values, arrayCalculation.values);
  }

  @Override
  public int hashCode() {
    return Objects.hash(colNames, values);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ArrayCalculation {\n");
    
    sb.append("    colNames: ").append(toIndentedString(colNames)).append("\n");
    sb.append("    values: ").append(toIndentedString(values)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

