/*
 * Jaqpot API
 * Jaqpot v4 (Quattro) is the 4th version of a YAQP, a RESTful web service which can be used to train machine learning models and use them to obtain toxicological predictions for given chemical compounds or engineered nano materials. The project is written in Java8 and JEE7.
 *
 * OpenAPI spec version: 4.0.3
 * Contact: hampos@me.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package jaqpot.client.model;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModelProperty;

/**
 * Substance
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2017-02-09T12:17:06.729Z")
public class Substance {
  @SerializedName("name")
  private String name = null;

  @SerializedName("ownerUUID")
  private String ownerUUID = null;

  @SerializedName("URI")
  private String URI = null;

  public Substance name(String name) {
    this.name = name;
    return this;
  }

   /**
   * Get name
   * @return name
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public Substance ownerUUID(String ownerUUID) {
    this.ownerUUID = ownerUUID;
    return this;
  }

   /**
   * Get ownerUUID
   * @return ownerUUID
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getOwnerUUID() {
    return ownerUUID;
  }

  public void setOwnerUUID(String ownerUUID) {
    this.ownerUUID = ownerUUID;
  }

  public Substance URI(String URI) {
    this.URI = URI;
    return this;
  }

   /**
   * Get URI
   * @return URI
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getURI() {
    return URI;
  }

  public void setURI(String URI) {
    this.URI = URI;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Substance substance = (Substance) o;
    return Objects.equals(this.name, substance.name) &&
        Objects.equals(this.ownerUUID, substance.ownerUUID) &&
        Objects.equals(this.URI, substance.URI);
  }

  @Override
  public int hashCode() {
    return Objects.hash(name, ownerUUID, URI);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Substance {\n");
    
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    ownerUUID: ").append(toIndentedString(ownerUUID)).append("\n");
    sb.append("    URI: ").append(toIndentedString(URI)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

