/*
 * Jaqpot API
 * Jaqpot v4 (Quattro) is the 4th version of a YAQP, a RESTful web service which can be used to train machine learning models and use them to obtain toxicological predictions for given chemical compounds or engineered nano materials. The project is written in Java8 and JEE7.
 *
 * OpenAPI spec version: 4.0.3
 * Contact: hampos@me.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package jaqpot.client.model;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModelProperty;

/**
 * UserQuota
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2017-02-09T12:17:06.729Z")
public class UserQuota {
  @SerializedName("userId")
  private String userId = null;

  @SerializedName("tasks")
  private Long tasks = null;

  @SerializedName("tasksRunning")
  private Long tasksRunning = null;

  @SerializedName("models")
  private Long models = null;

  @SerializedName("algorithms")
  private Long algorithms = null;

  @SerializedName("datasets")
  private Long datasets = null;

  @SerializedName("bibtex")
  private Long bibtex = null;

  @SerializedName("reports")
  private Long reports = null;

  public UserQuota userId(String userId) {
    this.userId = userId;
    return this;
  }

   /**
   * Get userId
   * @return userId
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getUserId() {
    return userId;
  }

  public void setUserId(String userId) {
    this.userId = userId;
  }

  public UserQuota tasks(Long tasks) {
    this.tasks = tasks;
    return this;
  }

   /**
   * Get tasks
   * @return tasks
  **/
  @ApiModelProperty(example = "null", value = "")
  public Long getTasks() {
    return tasks;
  }

  public void setTasks(Long tasks) {
    this.tasks = tasks;
  }

  public UserQuota tasksRunning(Long tasksRunning) {
    this.tasksRunning = tasksRunning;
    return this;
  }

   /**
   * Get tasksRunning
   * @return tasksRunning
  **/
  @ApiModelProperty(example = "null", value = "")
  public Long getTasksRunning() {
    return tasksRunning;
  }

  public void setTasksRunning(Long tasksRunning) {
    this.tasksRunning = tasksRunning;
  }

  public UserQuota models(Long models) {
    this.models = models;
    return this;
  }

   /**
   * Get models
   * @return models
  **/
  @ApiModelProperty(example = "null", value = "")
  public Long getModels() {
    return models;
  }

  public void setModels(Long models) {
    this.models = models;
  }

  public UserQuota algorithms(Long algorithms) {
    this.algorithms = algorithms;
    return this;
  }

   /**
   * Get algorithms
   * @return algorithms
  **/
  @ApiModelProperty(example = "null", value = "")
  public Long getAlgorithms() {
    return algorithms;
  }

  public void setAlgorithms(Long algorithms) {
    this.algorithms = algorithms;
  }

  public UserQuota datasets(Long datasets) {
    this.datasets = datasets;
    return this;
  }

   /**
   * Get datasets
   * @return datasets
  **/
  @ApiModelProperty(example = "null", value = "")
  public Long getDatasets() {
    return datasets;
  }

  public void setDatasets(Long datasets) {
    this.datasets = datasets;
  }

  public UserQuota bibtex(Long bibtex) {
    this.bibtex = bibtex;
    return this;
  }

   /**
   * Get bibtex
   * @return bibtex
  **/
  @ApiModelProperty(example = "null", value = "")
  public Long getBibtex() {
    return bibtex;
  }

  public void setBibtex(Long bibtex) {
    this.bibtex = bibtex;
  }

  public UserQuota reports(Long reports) {
    this.reports = reports;
    return this;
  }

   /**
   * Get reports
   * @return reports
  **/
  @ApiModelProperty(example = "null", value = "")
  public Long getReports() {
    return reports;
  }

  public void setReports(Long reports) {
    this.reports = reports;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    UserQuota userQuota = (UserQuota) o;
    return Objects.equals(this.userId, userQuota.userId) &&
        Objects.equals(this.tasks, userQuota.tasks) &&
        Objects.equals(this.tasksRunning, userQuota.tasksRunning) &&
        Objects.equals(this.models, userQuota.models) &&
        Objects.equals(this.algorithms, userQuota.algorithms) &&
        Objects.equals(this.datasets, userQuota.datasets) &&
        Objects.equals(this.bibtex, userQuota.bibtex) &&
        Objects.equals(this.reports, userQuota.reports);
  }

  @Override
  public int hashCode() {
    return Objects.hash(userId, tasks, tasksRunning, models, algorithms, datasets, bibtex, reports);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class UserQuota {\n");
    
    sb.append("    userId: ").append(toIndentedString(userId)).append("\n");
    sb.append("    tasks: ").append(toIndentedString(tasks)).append("\n");
    sb.append("    tasksRunning: ").append(toIndentedString(tasksRunning)).append("\n");
    sb.append("    models: ").append(toIndentedString(models)).append("\n");
    sb.append("    algorithms: ").append(toIndentedString(algorithms)).append("\n");
    sb.append("    datasets: ").append(toIndentedString(datasets)).append("\n");
    sb.append("    bibtex: ").append(toIndentedString(bibtex)).append("\n");
    sb.append("    reports: ").append(toIndentedString(reports)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

