/*
 * Jaqpot API
 * Jaqpot v4 (Quattro) is the 4th version of a YAQP, a RESTful web service which can be used to train machine learning models and use them to obtain toxicological predictions for given chemical compounds or engineered nano materials. The project is written in Java8 and JEE7.
 *
 * OpenAPI spec version: 4.0.3
 * Contact: hampos@me.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package jaqpot.client.api;

import jaqpot.client.ApiException;
import jaqpot.client.model.Report;
import org.junit.Test;
import org.junit.Ignore;

/**
 * API tests for ReadacrossApi
 */
@Ignore
public class ReadacrossApiTest {

    private final ReadacrossApi api = new ReadacrossApi();

    
    /**
     * Creates Read Across Report
     *
     * Creates Read Across Report
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void interLabTestReadAcrossTest() throws ApiException {
        String title = null;
        String descriptions = null;
        String datasetUri = null;
        String predictionFeature = null;
        String parameters = null;
        String subjectid = null;
        Report response = api.interLabTestReadAcross(title, descriptions, datasetUri, predictionFeature, parameters, subjectid);

        // TODO: test validations
    }
    
}
