/*
 * Jaqpot API
 * Jaqpot v4 (Quattro) is the 4th version of a YAQP, a RESTful web service which can be used to train machine learning models and use them to obtain toxicological predictions for given chemical compounds or engineered nano materials. The project is written in Java8 and JEE7.
 *
 * OpenAPI spec version: 4.0.3
 * Contact: hampos@me.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package jaqpot.client.api;

import jaqpot.client.ApiException;
import jaqpot.client.model.Task;
import org.junit.Test;
import org.junit.Ignore;

/**
 * API tests for TaskApi
 */
@Ignore
public class TaskApiTest {

    private final TaskApi api = new TaskApi();

    
    /**
     * Deletes a Task of given ID
     *
     * Deletes a Task given its ID in the URI. When the DELETE method is applied, the task is interrupted and tagged as CANCELLED. Note that this method does not return a response on success. If the task does not exist, an error report will be returned to the client accompanied by an HTTP status code 404. Note also that authentication and authorization restrictions apply, so clients need to be authenticated with a valid token and have appropriate rights to be able to successfully apply this method.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void deleteTaskTest() throws ApiException {
        String id = null;
        String subjectid = null;
        api.deleteTask(id, subjectid);

        // TODO: test validations
    }
    
    /**
     * Finds Task by Id
     *
     * Finds specified Task
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getTaskTest() throws ApiException {
        String id = null;
        String subjectid = null;
        api.getTask(id, subjectid);

        // TODO: test validations
    }
    
    /**
     * Finds all Tasks
     *
     * Finds all Tasks from Jaqpot Dataset. One may specify various search criteria such as the task creator of the task status.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void listTasksTest() throws ApiException {
        String subjectid = null;
        String status = null;
        Integer start = null;
        Integer max = null;
        api.listTasks(subjectid, status, start, max);

        // TODO: test validations
    }
    
    /**
     * Poll Task by Id
     *
     * Implements long polling
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void pollTest() throws ApiException {
        String id = null;
        String subjectid = null;
        Task response = api.poll(id, subjectid);

        // TODO: test validations
    }
    
}
